DELETE http://localhost:3001/api/notes/606203746d5dbb14556fb509
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTdmNGIxNTE4NjM3NWI1MDljZDNjZCIsInVzZXJuYW1lIjoiZGFsbWFndWVyIiwiaWF0IjoxNjE3MDM2MTAzLCJleHAiOjE2MTc2NDA5MDN9.QqTVI_PtgLraLmKvSeZFJRUt7_VG7WoHTmRXEtU4Kwk