POST http://localhost:3001/api/notes
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNTdmNGIxNTE4NjM3NWI1MDljZDNjZCIsInVzZXJuYW1lIjoiZGFsbWFndWVyIiwiaWF0IjoxNjE3MDM2MTAzLCJleHAiOjE2MTc2NDA5MDN9.QqTVI_PtgLraLmKvSeZFJRUt7_VG7WoHTmRXEtU4Kwk

{
  "content": "Una Nota para borrar",
  "important": true
}

###

POST http://localhost:3001/api/notes
content-type: application/json

{
}
